server:
  port: 10010

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix: /api # 路由前缀
  routes:
    item-service: /item**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长 5000ms
ribbon:
  ReadTimeout: 5000 # ribbon 读取超时时长
  ConnectTimeout: 3000 # ribbon链接超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重启次数